#!/bin/sh

SIZE="-s 64"
STEPS="-t 20000"
AVE="-a 1000"

set -e
echo -n Single temperature, drawing progress graph...
../src/ising -T 1 -d progress.gif > /dev/null
echo OK

if [ -f /proc/cpuinfo ] ;
then
	CPUS="-j `grep -c ^processor /proc/cpuinfo`"
fi

echo -n kT=0 to kT=5J...
../src/runs -o ising.dat -g ising.pdf -f heat.pdf -d heat.pdf -P 1 0 -2 4 -n 50 $AVE $STEPS $SIZE $CPUS
echo OK
grep -E '^(beta|Tc) *=' fit.log | tail -n 2
echo -n kT around kT_c...
../src/runs -o detail.dat -1 2 -2 2.5 -n 30 $AVE $STEPS $SIZE $CPUS
echo OK
echo '(re)plotting...'
gnuplot 2> /dev/null <<"END"
Tc = 2.3
C(x) = 8 * (log(sqrt(2)) +log(x*Tc) - log(abs(x-Tc)) -1 - pi/4) / (Tc**2 *pi)
fit [2:3] C(x) '< cat detail.dat ising.dat' u 1:7 via Tc
set term pdf
set output 'heat2.pdf'
set xlabel 'kT/J'
set ylabel 'Specific Heat Capacity/k'
set yrange [0:2.5]
set xtics rotate by -45 add ('Tc(Onsager)' 2.269185314)
set samples 10000
plot '' u 1:7 title 'Cf', '' u 1:6 title 'Cd', C(x) title 'Fit to Cf'
END
grep -E '^(Tc) *=' fit.log | tail -n 1

echo plotting...
gnuplot 2> /dev/null <<"END"
Tc = 2.4
beta = 0.1
c = 1
func(x) = x < Tc ? c*(Tc - x) ** beta : 0
fit func(x) 'detail.dat' u 1:2:3 via beta, Tc,c
set term pdf
set output 'detail.pdf'
set xlabel 'kT/J'
set ylabel 'Magnetization'
set yrange [0:1]
set xtics rotate by -45 add ('Tc(Onsager)' 2.269185314)
plot 'ising.dat' u 1:2:3 w yerrorbars t 'Wide data', 'detail.dat' u 1:2:3 w yerrorbars t 'Fit Data', func(x) t "M = c(Tc-T)^m"
END
grep -E '^(beta|c|Tc) *=' fit.log | tail -n 3
