#!/bin/sh

set -e
echo -n Single temperature, drawing progress graph...
../src/ising -T 1 -d progress.gif > /dev/null
echo OK

if [ -f /proc/cpuinfo ] ;
then
	CPUS="-j `grep -c ^processor /proc/cpuinfo`"
fi

echo -n kT=0 to kT=5J...
../src/runs -o ising.dat -g ising.png -1 0 -2 5 -n 100 -s 50 -t 2000 $CPUS
echo OK

echo -n kT around kT_c...
../src/runs -o detail.dat -1 1.8 -2 2.3 -s 50 -t 10000 -n 20 $CPUS
echo -n plotting...
gnuplot <<"END"
Tc = 2.269
beta = 0.1
c = 1
func(x) = x < Tc ? c * (Tc - x) ** beta : 0
fit func(x) 'detail.dat' u 1:(abs($2)) via beta, Tc
set term png size 1024,768
set output 'detail.png'
set xlabel 'kT/J'
set ylabel 'Magnetization'
set xtics rotate by -45 add ('Tc(Onsager)' 2.269185314)
#set xrange [1:2.5]
plot 'ising.dat' u 1:(abs($2)) t 'Wide data', 'detail.dat' u 1:(abs($2)) t 'Fit Data', func(x) t "M = c(Tc-T)^m"
END
echo -n OK